#!/bin/bash

# Make sure the user data directory is owned by the developer user
if [ -d /home/iotivity/.eclipse ]; then
  sudo chown iotivity:iotivity /home/iotivity/.eclipse
fi
exec /opt/eclipse/eclipse